#ifndef _LIBCLUTTERMM_WRAP_INIT_H
#define _LIBCLUTTERMM_WRAP_INIT_H

/* wrap_init.h
 *
 * Copyright (C) 2002-2014 The cluttermm Development Team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

// wrap_init.cc is generated by tools/generate_wrap_init.pl

namespace Clutter
{

// TODO: This is needed in wrap_init.cc, but to get it there in a better way than
// putting it here requires a change in generate_wrap_init.pl.
#define CLUTTER_DISABLE_DEPRECATION_WARNINGS 1

void wrap_init();

} //namespace Clutter

#endif // _LIBCLUTTERMM_WRAP_INIT_H
