local_goocanvasmm_lib = $(top_builddir)/goocanvas/goocanvasmm/libcluttermm-0.1.la

LIBS  = $(CLUTTERMM_LIBS) $(local_goocanvasmm_lib) 

all_includes = -I$(top_builddir)/goocanvas -I$(top_srcdir)/goocanvas \
               $(CLUTTERMM_CFLAGS)
                     
DEFS = @DEFS@
DEFAULT_INCLUDES =
INCLUDES = -I. -I$(srcdir) $(strip $(all_includes))

